Add spherical test
open-atmos/PyMPDATA-MPI pull request #64
Opened 2023-04-28 11:07 UTC by Delcior

2023-08-27 11:44 UTC, slayoo requested changes

2023-08-27 11:44 UTC, slayoo commented on tests/local/contract_tests/test_single_vs_multi_node.py
>              plot_path = Path(os.environ["CI_PLOTS_PATH"]) / Path(
here we need to include scenario name to avoid overwriting files, right?

2023-08-27 11:44 UTC, slayoo commented on PyMPDATA_MPI/mpi_periodic.py
> +# pylint: disable=invalid-name,unused-argument,c-extension-no-member,too-many-arguments,line-too-long,duplicate-code
let's fix whatever is requireing `line-too-long` and `duplicate-code`!

2023-08-27 11:44 UTC, slayoo commented on PyMPDATA_MPI/mpi_periodic.py
>  IRRELEVANT = 666
this seem not used anymore

2023-08-27 11:44 UTC, slayoo commented on README.md
> +#TODO #80: REMOVE PBS FROM DIAG
let's just remove it! :)

2023-08-27 11:44 UTC, slayoo commented on scenarios/spherical.py
> +# pylint: disable=missing-class-docstring,invalid-name,too-many-locals,too-many-arguments,c-extension-no-member, no-member
let's aim at removing all these pylint-disable comments

2023-08-27 11:44 UTC, slayoo commented on scenarios/cartesian.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring,invalid-name,too-few-public-methods,too-many-locals
let's aim at removing all these pylint-disable comments

2023-08-27 11:44 UTC, slayoo commented on tests/local/contract_tests/test_single_vs_multi_node.py
>  # based on PyMPDATA README example
this comment is not valid anymore

2023-08-27 11:44 UTC, slayoo commented on .github/workflows/tests+pypi.yml
>              export CI_PLOTS_PATH=plots/$arbitrarily_selected_artefact_set
does it need any new logic to handle multiple scenarios?

2023-08-29 07:05 UTC, slayoo requested changes

2023-08-29 07:05 UTC, slayoo commented on scenarios/spherical.py
> +        print(Cx_max)
debug leftover

2023-08-29 07:05 UTC, slayoo commented on scenarios/spherical.py
> +        print(Cy_max)
debug leftover

2023-08-29 08:06 UTC, Delcior commented on PyMPDATA_MPI/mpi_periodic.py
>  IRRELEVANT = 666
removed

2023-08-29 09:02 UTC, slayoo commented on README.md
>  Rectangular boxes indicate pip-installable Python packages (click to go to pypi.org package site).
BTW, we need to modify path for animations so that th Scenario component is featured

2023-08-29 20:22 UTC, slayoo approved these changes

2023-08-29 20:23 UTC, merged